server:
  port: 8002

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/todo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size : 100
    generate-ddl: true
